version: 2
jobs:
  build:
    docker:
      - image: shopware/development
    working_directory: /var/www/html
    steps:
      - run:
          name: Clear html folder
          command: |
            rm -rf index.html
      - checkout
      - restore_cache:
          key: -v1-{{ checksum "/var/www/html/composer.json"}}
      - run:
          name: Composer install
          command: |
            composer install --prefer-dist
      - save_cache:
          key: -v1-{{ checksum "/var/www/html/composer.json"}}
          paths:
            - /var/www/html/vendor
      - run:
          name: Run Phpunit With test suite unit test
          command: |
            vendor/bin/phpunit --testsuite="MultiSafepay Unit tests" --bootstrap="vendor/autoload.php"
  push:
    docker:
      - image: circleci/php:7.2-apache-node-browsers
    working_directory: /var/www/html
    steps:
      - add_ssh_keys:
            fingerprints:
              - "34:96:fa:6e:21:0f:15:fd:2f:37:e8:08:79:0d:22:e3"
      - checkout
      - run:
          name: Git push
          command: |
            git push -u github@github.com:mikededecker/private-repo.git push
workflows:
  version: 2
  default_check:
    jobs:
      - build
      - push:
          requires:
            - build