name: Sync
on: [push]
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Git push
        run: |
          git remote add upstream https://mikededecker:${{ secrets.ACTIONS_TOKEN }}@github.com/${{ secrets.PUSH_REPO }}
          git push upstream HEAD:push
        env:
          CI: true
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
      - name: push tags
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          git remote add upstream https://mikededecker:${{ secrets.ACTIONS_TOKEN }}@github.com/${{ secrets.PUSH_REPO }}
          git push upstream --tags
