name: Build
on: [push]
jobs:
  sync:
    runs-on: ubuntu-latest
    name: Php unit test
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Add remote
        run: git remote add upstream git:${{ secrets.ACTIONS_TOKEN }}@github.com/${{ secrets.PUSH_REPO }}
      - name: Push
        run: echo $GITHUB_REF
