name: Build
on: [push]
jobs:
  sync:
    runs-on: ubuntu-latest
    name: Php unit test
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Add remote
        run: |
          pwd
          ls -a
